### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by freeman-lab** [tab58/ndarray-optimization#1]
Hey! This is a neat package. Realize it's not quite finished, but we're already finding it useful in a project for a small time series optimization problem (https://github.com/carbonplan/margo-js). Any chance you would mind publishing to npm? We'd love to add it as a proper dependency. 

Happy also to help do it if that would be easier. Thanks!

**Comment by tab58** [comment]
You're right, it's definitely not finished. I was working on an SQP algorithm, got caught up in the details, and left it unfinished. I'd be lying if I said your interest hasn't at least reawakened the desire to finish it.

I can publish it to NPM if you're finding some value in it. If you want to contribute, feel free to submit some PRs.

**Comment by tab58** [comment]
Published as 0.1.0 because it's definitely not at v1.0 yet.
